dist: xenial
sudo: required
language: C
before_install:

# Remove other versions of llvm/clang 
- sudo apt-get purge -y -qq libllvm3.4 llvm-3.4 llvm* libllvm* clang*
- sudo rm -Rf /usr/local/clang
- sudo rm -Rf /usr/local/clang-5.0.0

# Install dependencies
- sudo apt-get -qq update
- sudo apt-get -qq upgrade -y
- sudo apt-get install -y cmake ninja-build build-essential zlib1g-dev libffi-dev libedit-dev libncurses5-dev libboost-dev wget tar doxygen

# Clone LLVM/Clang repos
- cd ..
- git clone https://github.com/llvm-mirror/llvm.git llvm
- cd llvm
- git checkout release_39
- cd tools
- git clone https://github.com/llvm-mirror/clang.git clang
- cd clang
- git checkout release_39
- cd ../..
- mkdir build && cd build

# Build and install LLVM/Clang 3.9.1
- CC=gcc CXX=g++ cmake -DLLVM_ENABLE_CXX1Y=true -DLLVM_ENABLE_RTTI=ON -DLLVM_TARGET_ARCH="X86" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_ENABLE_FFI=ON -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -G Ninja ..
- ninja
- sudo ninja install

# Download ParadisEO
- cd $TRAVIS_BUILD_DIR
- cd ..
- wget https://gforge.inria.fr/frs/download.php/31732/ParadisEO-2.0.1.tar.gz
- tar xvfz ParadisEO-2.0.1.tar.gz > /dev/null
- rm -f ParadisEO-2.0.1.tar.gz

# Build and install ParadisEO
- cd ParadisEO-2.0
- mkdir build && cd build
- sed -i "s/CMAKE_MINIMUM_REQUIRED(VERSION 2.6)/CMAKE_MINIMUM_REQUIRED(VERSION 3.3)/g" ../eo/CMakeLists.txt
- cmake .. -G Ninja
- ninja
- sudo ninja install

install:
# Build and install Bellerophon
- cd $TRAVIS_BUILD_DIR
- mkdir build && cd build
- LLVM_LIBS="$(llvm-config --components)" && sed -i "s/insert-llvm-libs-here/${LLVM_LIBS}/g" ../CMakeLists.txt
- sed -i "s/all-targets //g" ../CMakeLists.txt
- sudo sed -i 's/list(APPEND link_components "jit")/list(APPEND link_components "mcjit")/g' /usr/lib/cmake/llvm/LLVM-Config.cmake
- cmake .. -DCMAKE_MODULE_PATH=$TRAVIS_BUILD_DIR/../ParadisEO-2.0/cmake/module/ -G Ninja
- ninja
- sudo ninja install

script:
- llvm-config --version
- clang --version
- bellerophon -version
